# step 1 bring the Base Image

FROM node:24

#step 2 create a folder where code can stay

WORKDIR /app

#step 3 copyt he code from host machine to the container

COPY . .

#step 4 install the req dependencies

RUN npm install

#step 5 expose the port number for documnetation purpose

EXPOSE 5173

#step 6 run the application
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]